<?php

namespace AppBundle\Repository;

/**
 * MagasinierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinierRepository extends \Doctrine\ORM\EntityRepository
{
}
