<?php

namespace AppBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findList(){
        
        $orderby = array('nompersonne' => 'ASC', 'prenompersonne' => 'ASC');
        
        return $this->findBy(array(), $orderby);
    }      

    public function findById($nom, $prenom){
        
        $keys = array("nompersonne" => $nom, "prenompersonne" => $prenom);
        $orderby = array('nompersonne' => 'ASC', 'prenompersonne' => 'DESC');
        
        return $this->find($keys, $orderby);
    }    

      
}
