<?php

namespace AppBundle\Repository;

/**
 * Produit_dans_panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_dans_panierRepository extends \Doctrine\ORM\EntityRepository
{
}
