AppBundle\Entity\Panier:
    repositoryClass: AppBundle\Repository\PanierRepository
    type: entity
    table: panier
    id:
        numpanier:
            type: integer
            generator:
                strategy:
                    IDENTITY
    fields:
        etat:
            type: string
            nullable: false
            columnDefinition: ENUM('Non validé', 'En cours de traitement', 'Traité')